export const ANSIDateQualifier: { [key: string]: string } = {
  "001": "Cancel After This Date/Time",
  "002": "Delivery Requested On This Date/Time",
  "003": "Invoice Date/Time",
  "004": "Purchase Order Date/Time",
  "005": "Sailing Date/Time",
  "006": "Solid Date/Time",
  "007": "Effective Date/Time",
  "008": "Purchase Order Received",
  "009": "Process Date/Time",
  "010": "Requested Ship Date/Time",
  "011": "Shipped On This Date/Time",
  "012": "Terms Discount Due Date/Time",
  "013": "Terms Net Due Date/Time",
  "014": "Deferred Payment Date/Time",
  "015": "Promotion Start",
  "016": "Promotion End",
  "017": "Estimated Delivery Date/Time",
  "018": "Date/Time Available/Constructive Placement",
  "019": "Date/Time Unloaded",
  "020": "Check Date/Time",
  "021": "Charge Back Date/Time",
  "022": "Freight Bill Date/Time",
  "023": "Promotion Order Date/Time - Start",
  "024": "Promotion Order Date/Time - End",
  "025": "Promotion Ship Date/Time - Start",
  "026": "Promotion Ship Date/Time - End",
  "027": "Promotion Requested Delivery Date/Time - Start",
  "028": "Promotion Requested Delivery Date/Time - End",
  "029": "Promotion Performance Delivery Date/Time - Start",
  "030": "Promotion Performance Delivery Date/Time - End",
  "031": "Promotion Invoice Performance Delivery Date/Time - Start",
  "032": "Promotion Invoice Performance Delivery Date/Time - End",
  "033": "Promotion Floor Stock Protect Date/Time - Start",
  "034": "Promotion Floor Stock Protect Date/Time - End",
  "035": "Delivered On This Date/Time",
  "036": "Expiration Date/Time",
  "037": "Ship Not Before Date/Time",
  "038": "Ship Not Later Than Date/Time",
  "039": "Ship Week Of Date/Time",
  "040": "Status Date (After And Including)",
  "041": "Status Date (Prior And Including)",
  "042": "Superseded Date",
  "043": "Publication Date",
  "044": "Received On This Date",
  "045": "Cumulative Quantity Start Date",
  "046": "Cumulative Quantity End Date",
  "047": "Buyer's Local Time",
  "048": "Seller's Local Time",
  "049": "Confirmed Date",
  "050": "Received On This Date",
  "051": "Cumulative Quantity Start Date",
  "052": "Cumulative Quantity End Date",
  "053": "Buyer's Local Time",
  "054": "Seller's Local Time",
  "055": "Confirmed Date",
  "056": "Estimated Port Of Entry Date",
  "057": "Actual Port Of Entry Date",
  "058": "Customs Clearance Date",
  "059": "Inland Ship Date",
  "060": "Engineering Change Level Date",
  "061": "Cancel If Not Delivered By This Date",
  "062": "Blueprint Date",
  "063": "Do Not Deliver After This Date",
  "064": "Do Not Deliver Before This Date",
  "065": "1st Schedule Delivery Date",
  "066": "1st Schedule Ship Date",
  "067": "Current Schedule Delivery Date",
  "068": "Current Schedule Ship Date",
  "069": "Promised For Delivery (Date/Time)",
  "070": "Scheduled For Delivery (After And Including)",
  "071": "Requested For Delivery (After And Including)",
  "072": "Promised For Delivery (After And Including)",
  "073": "Scheduled For Delivery (Prior To And Including)",
  "074": "Requested For Delivery (Prior To And Including)",
  "075": "Promised For Delivery (Prior To And Including)",
  "076": "Scheduled For Delivery (Week Of)",
  "077": "Requested For Delivery (Week Of)",
  "078": "Promised For Delivery (Week Of)",
  "079": "Promised For Shipment(Date/Time)",
  "080": "Scheduled For Shipment(AfterAndIncluding)",
  "081": "Requested For Shipment (After And Including)",
  "082": "Promised For Shipment (After And Including)",
  "083": "Scheduled For Shipment (Prior To And Including)",
  "084": "Requested For Shipment (Prior To And Including)",
  "085": "Promised For Shipment (Prior To And Including)",
  "086": "Scheduled For Shipment (Week Of)",
  "087": "Requested For Shipment (Week Of)",
  "088": "Promised For Shipment (Week Of)",
  "089": "Inquiry Date",
  "090": "Report Start Date",
  "091": "Report End Date",
  "092": "Contract Effective Date",
  "093": "Contract Expiration Date",
  "094": "Manufacturing Date",
  "095": "Bill of Lading Date",
  "096": "Date/Time Of Discharge",
  "097": "Transaction Creation Date",
  "098": "Bid (Effective) Date",
  "099": "Bid-Open Date (Date Bids Will Be Opened)",
  "100": "No Shipping Schedule Established As Of Date/Time",
  "101": "No Production Schedule Established As Of Date/Time",
  "102": "Expect To Ship By Date",
  "103": "Expect To Ship By Week Of Date",
  "104": "Revised Expect To Ship By Date",
  "105": "Revised Expect To Ship By Week Of Date",
  "106": "Required By Date",
  "107": "Deposit Date/Time",
  "108": "Postmark Date",
  "109": "Date/Time Received At Lockbox",
  "110": "Agreed Upon Scheduled Ship",
  "116": "Scheduled Interchange Delivery",
  "132": "Estimated Delivery Date/Time",
  "214": "Date Of Repair/Service",
};
