export const ANSIUnitOfMeasure: { [key: string]: string } = {
  "01": "Actual Pounds",
  "02": "Statute Mile",
  "03": "Seconds",
  "04": "Small Spray",
  "05": "Lifts",
  "08": "Heat Lots",
  "10": "Group",
  "11": "Outfit",
  "12": "Packet",
  "13": "Ration",
  "14": "Shot",
  "15": "Stick",
  "24": "Theoretical Pounds",
  "26": "Actual Tons",
  "27": "Theoretical Tons",
  "31": "Catchweight",
  "50": "Actual Kilograms",
  "51": "Actual Tonnes",
  "53": "Theoretical Kilograms",
  "54": "Theoretical Tonnes",
  "56": "Sitas",
  "58": "Net Kilograms",
  "59": "Parts Per Million",
  "60": "Percent Weight",
  "61": "Parts Per Billion",
  "62": "Percent Per 100 Hours",
  "63": "Failure Rate In Time",
  "64": "Pounds Per Square Inch Gauge",
  "65": "Coulomb (A Unit of Charge)",
  "66": "Oersteds",
  "67": "Siemens (A Unit of Admittance)",
  "68": "Ampere",
  "69": "Test Specific Scale",
  "70": "Volt",
  "71": "Volt-Ampere Per Pound",
  "72": "Watts Per Pound",
  "73": "Ampere Turn Per Centimeter",
  "74": "Milli Pascals",
  "75": "Cycles",
  "76": "Gauss",
  "77": "Mil",
  "78": "Kilogauss",
  "79": "Electron Volt",
  "80": "Pounds Per Square Inch (Absolute)",
  "81": "Henry (A Unit of Inductance)",
  "82": "Ohm (A Unit of Resistance)",
  "83": "Farad (A Unit of Capacitance)",
  "84": "Kilo Pounds Per Square Inch (KSI)",
  "85": "Foot Pounds",
  "86": "Joules",
  AA: "Ball",
  AC: "Acre",
  AM: "Ampoule AP Aluminum Pounds Only",
  AS: "Assortment",
  AY: "Assembly",
  B2: "Bunks",
  B3: "Batting Pound",
  B4: "Barrel, Imperial",
  B5: "Billet",
  B6: "Bun",
  B7: "Cycles",
  B8: "Board",
  B9: "Batt",
  BA: "Bale",
  BB: "Base Box",
  BC: "Bucket",
  BD: "Bundle",
  BE: "Beam",
  BF: "Board Feet",
  BG: "Bag",
  BH: "Brush",
  BI: "Bar",
  BJ: "Band",
  BK: "Book",
  BL: "Block",
  BM: "Bolt",
  BN: "Bulk",
  BO: "Bottle",
  BP: "100 Board Feet",
  BQ: "Brake horse power",
  BR: "Barrel",
  BS: "Basket",
  BT: "Belt",
  BU: "Bushel",
  BV: "Bushel, Dry Imperial",
  BW: "Base Weight",
  BX: "Box",
  BY: "British Thermal Unit (BTU)",
  BZ: "Million BTUs",
  C1: "Composite Product Pounds (total weight)",
  C2: "Carset",
  C3: "Centiliter",
  C4: "Carload",
  C5: "Cost",
  C6: "Cell",
  C7: "Centipoise (CPS)",
  C8: "Cubic Decimeter",
  C9: "Coil Group",
  CA: "Case",
  CB: "Carboy",
  CC: "Cubic Centimeter",
  CD: "Carat",
  CE: "Centigrade, Celsius",
  CF: "Cubic Feet",
  CG: "Card",
  CH: "Container",
  CI: "Cubic Inches",
  CJ: "Cone",
  CK: "Connector",
  CL: "Cylinder",
  CM: "Centimeter",
  CN: "Can",
  CO: "Count",
  CP: "Crate",
  CQ: "Cartridge",
  CR: "Cubic Meter",
  CS: "Cassette",
  CT: "Carton",
  CU: "Cup",
  CV: "Cover",
  CW: "Hundred Pound (CWT)",
  CX: "Coil",
  CY: "Cubic Yard",
  CZ: "Combo",
  DA: "Days",
  DB: "Dry Pound",
  // "DB": "Dry Pounds",
  DC: "Disk (Disc)",
  DD: "Degree",
  DE: "Deal",
  DF: "Dram",
  DG: "Decigram",
  DH: "Miles",
  DI: "Dispenser",
  DK: "Kilometers",
  DL: "Deciliter",
  DM: "Decimeter",
  DP: "Dozen Pair",
  DR: "Drum",
  DS: "Display",
  DT: "Dry Ton",
  DZ: "Dozen",
  E3: "Inches, Fraction-Average",
  E4: "Inches, Fraction-Minimum",
  E5: "Inches, Fraction-Actual",
  E7: "Inches, Decimal-Average",
  E8: "Inches, Decimal-Actual",
  E9: "English (Feet, Inches)",
  EA: "Each",
  ED: "Inches, Decimal-Nominal",
  EF: "Inches, Fraction-Nominal",
  EM: "Inches, Fraction-Minimum",
  EP: "Eleven pack",
  EV: "Envelope",
  EX: "Feet, Inches and Fraction",
  EY: "Feet, Inches",
  EZ: "Feet and Decimal",
  FA: "Fahrenheit",
  FC: "1000 Cubic Feet",
  FM: "Million Cubic Feet",
  FO: "Fluid Ounce",
  FP: "Pounds Per Square Foot",
  FT: "Foot",
  GA: "Gallon",
  GB: "Gallons/Day",
  GG: "Great Gross (Dozen Gross)",
  GH: "One-half Gallon",
  GI: "Imperial Gallons",
  GL: "Grams Per Liter",
  GM: "Grams Per Square Meter",
  GN: "Gross Gallons",
  GR: "Gram",
  GS: "Gross",
  GY: "Gross Yard",
  GZ: "Gage Systems",
  HA: "Hank (100 feet of rope)",
  HB: "Hundred Boxes",
  HC: "Hundred Count",
  HD: "Half Dozen",
  HE: "Hundredth of a Carat",
  HF: "Hundred Feet",
  HG: "Hectograms",
  HH: "Hundred Cubic Feet",
  HI: "Hundred Sheets",
  HJ: "Horse power",
  HK: "Hundred Kilograms",
  HL: "Hundred Feet-Linear",
  HO: "Hundred Troy Ounces",
  HP: "Hundred Pounds",
  HR: "Hours",
  HS: "Hundred Square Feet",
  HT: "Half Hour",
  HU: "Hundred",
  HV: "Hundred Weight (Short)",
  HW: "Hundred Weight (Long)",
  HY: "Hundred Yards",
  IN: "Inch",
  JB: "Jumbo",
  JO: "Joint",
  JR: "Jar",
  JU: "Jug",
  KA: "Cake",
  KD: "Kilograms Decimal",
  KE: "Keg",
  KG: "Kilograms",
  KH: "Kilowatt Hour",
  KI: "Kilograms/Millimeter Width",
  KK: "100 Kilograms",
  KL: "Kilograms/Meter",
  KM: "Kilograms/Square Meter, Kilograms, Decimal",
  KN: "Kilometer",
  KT: "Kit",
  KV: "Kelvin",
  KW: "Kilograms Per Millimeter",
  LA: "Pounds Per Cubic Inch",
  LB: "Pound",
  LC: "Linear Centimeter",
  LE: "Lite",
  LF: "Linear Foot",
  LG: "Long Ton",
  LH: "Labor Hours",
  LI: "Linear Inch",
  LJ: "Large Spray",
  LK: "Link",
  LM: "Linear Meter",
  LN: "Length",
  LO: "Lot",
  LP: "Liquid Pounds",
  LR: "Layer",
  LS: "Lump Sum",
  LT: "Liter",
  LY: "Linear Yard",
  M1: "Milligrams per Liter",
  M2: "Millimeter-Actual",
  M3: "Mat",
  M4: "Monetary Value",
  M6: "Milligrams/Square Inch",
  MA: "Machine/Unit",
  MB: "Millimeter-Nominal",
  MC: "Microgram",
  ME: "Milligram",
  MF: "Milligrams/Square Foot Per Side",
  MG: "Metric Gross Tons",
  MH: "Microns",
  MI: "Metric",
  MJ: "Minutes",
  MK: "Milligrams Per Square Inch",
  ML: "Milliliter",
  MM: "Millimeter",
  MN: "Metric Net Ton",
  MO: "Months",
  MP: "Metric Ton",
  MQ: "1000 Meters",
  MR: "Meter",
  MS: "Square Millimeter",
  MT: "Metric Long Ton",
  MU: "Millicurie",
  MV: "Number of Mults",
  MW: "Metric Ton Kilograms",
  MX: "Mixed",
  MY: "Millimeter-Average",
  MZ: "Millimeter-Minimum",
  NB: "Barge",
  NC: "Car",
  NL: "Load",
  NM: "Nautical Mile",
  NN: "Train",
  NT: "Trailer",
  NV: "Vehicle",
  OL: "Ounces Liquid",
  OP: "Two-pack",
  OT: "Overtime Hours",
  OZ: "Ounces Avoirdupois",
  P1: "Percent",
  P2: "Pounds Per Foot",
  P3: "Three-Pack",
  P4: "Four-Pack",
  P5: "Five-Pack",
  P6: "Six-Pack",
  P7: "Seven-Pack",
  P8: "Eight-Pack",
  P9: "Nine-Pack",
  PA: "Pail",
  PB: "Pair Inches",
  PC: "Piece",
  PD: "Pad",
  PE: "Pounds Equivalent",
  PF: "Pallet (Lift)",
  PG: "Pounds Gross",
  PH: "Pack (Pak)",
  PI: "Pitch",
  PJ: "Pounds, Decimal-Pounds/Square Foot-Pound Gage",
  PK: "Package",
  PL: "Pallet/Unit Load",
  PM: "Pounds-Percentage",
  PN: "Pounds Net",
  PO: "Pounds Per Inch of Length",
  PP: "Plate",
  PR: "Pair",
  PS: "Pounds Per Square Inch",
  PT: "Pint",
  PV: "One-half Pint",
  PW: "Pounds Per Inch of Width",
  PX: "Pint, Imperial",
  PY: "Peck, Dry US",
  PZ: "Peck, Dry Imperial",
  Q1: "Quarter (Time)",
  QD: "Quarter Dozen",
  QR: "Quire",
  QS: "Quart, Dry US",
  QT: "Quart",
  QU: "Quart, Imperial",
  RA: "Rack",
  RD: "Rod",
  RE: "Reel",
  RG: "Ring",
  RK: "Roll-Metric Measure",
  RL: "Roll",
  RM: "Ream",
  RN: "Ream-Metric Measure",
  RO: "Round",
  SA: "Sandwich",
  SB: "Square Mile",
  SC: "Square Centimeter",
  SD: "Solid Pounds",
  SE: "Section",
  SF: "Square Foot",
  SG: "Segment",
  SH: "Sheet",
  SI: "Square Inch",
  SJ: "Sack",
  SK: "Split Tank Truck",
  SL: "Sleeve",
  SM: "Square Meter",
  SN: "Square Rod",
  SO: "Spool",
  SP: "Shelf Package",
  SQ: "Square",
  SR: "Strip",
  SS: "Sheet-Metric Measure",
  ST: "Set",
  SU: "Short Ton",
  SV: "Skid",
  SW: "Skein",
  SX: "Shipment",
  SY: "Square Yard",
  T1: "Thousand Pounds gross",
  TA: "Tenth Cubic Foot",
  TB: "Tube",
  TC: "Truck Load",
  TD: "Therms",
  TE: "Tote",
  TF: "Ten Square Yards",
  TG: "Gross Ton",
  TH: "Thousand",
  TI: "Thousand Square Inches",
  TJ: "Thousand Square Centimeters",
  TK: "Tank",
  TL: "Thousand Feet-Linear",
  TM: "Thousand Feet (Board)",
  TN: "Net Ton",
  TO: "Troy Ounce",
  TP: "Ten Pack",
  TQ: "Thousand Feet",
  TR: "Ten Square Feet",
  TS: "Thousand Square Feet",
  TT: "Thousand Linear Meters",
  TU: "Thousand Linear Yards",
  TV: "Thousand Kilograms",
  TW: "Thousand Pieces of Sheets",
  TX: "Troy Pound",
  TY: "Tray",
  TZ: "Thousand Cubic Feet",
  UN: "Unit",
  VI: "Vial",
  VT: "Voltage",
  WB: "Wet Pound",
  WE: "Wet Ton",
  WH: "Wheel",
  WI: "Weight Per Square Inch",
  WK: "Week",
  WP: "Pennyweight",
  WR: "Wrap",
  WT: "Wattage",
  YD: "Yard",
  YL: "100 Linear Yards",
  YR: "Years",
  YT: "Ten Yards",
  ZZ: "Mutually Defined",
};
