services:
  parser:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: parser
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${ENV_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${ENV_NAME}.rule=Host(`${HTTP_URI}`)"
      - "traefik.http.routers.${ENV_NAME}.service=${ENV_NAME}"
      - "traefik.http.routers.${ENV_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ENV_NAME}.middlewares=httpsredirect@file"

    networks:
      - web
    env_file:
      - stack.env
networks:
  web:
    external: true
